/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserPaymentAcceptanceConsentTokenRouteImport } from './routes/user-payment-acceptance/$consentToken'
import { Route as PortalTokenRouteImport } from './routes/portal/$token'
import { Route as AuthenticatedSheetRouteImport } from './routes/_authenticated/sheet'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedCapitalRouteImport } from './routes/_authenticated/capital'
import { Route as AuthenticatedBinRouteImport } from './routes/_authenticated/bin'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedLoansIndexRouteImport } from './routes/_authenticated/loans/index'
import { Route as AuthenticatedBorrowersIndexRouteImport } from './routes/_authenticated/borrowers/index'
import { Route as ApiSheetDownloadRouteImport } from './routes/api/sheet/download'
import { Route as ApiCronSheetSyncRouteImport } from './routes/api/cron/sheet-sync'
import { Route as ApiCronRemindersRouteImport } from './routes/api/cron/reminders'
import { Route as AuthenticatedLoansNewRouteImport } from './routes/_authenticated/loans/new'
import { Route as AuthenticatedLoansLoanIdRouteImport } from './routes/_authenticated/loans/$loanId'
import { Route as AuthenticatedBorrowersNewRouteImport } from './routes/_authenticated/borrowers/new'
import { Route as AuthenticatedBorrowersBorrowerIdRouteImport } from './routes/_authenticated/borrowers/$borrowerId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserPaymentAcceptanceConsentTokenRoute =
  UserPaymentAcceptanceConsentTokenRouteImport.update({
    id: '/user-payment-acceptance/$consentToken',
    path: '/user-payment-acceptance/$consentToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSheetRoute = AuthenticatedSheetRouteImport.update({
  id: '/sheet',
  path: '/sheet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCapitalRoute = AuthenticatedCapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBinRoute = AuthenticatedBinRouteImport.update({
  id: '/bin',
  path: '/bin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoansIndexRoute = AuthenticatedLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBorrowersIndexRoute =
  AuthenticatedBorrowersIndexRouteImport.update({
    id: '/borrowers/',
    path: '/borrowers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiSheetDownloadRoute = ApiSheetDownloadRouteImport.update({
  id: '/api/sheet/download',
  path: '/api/sheet/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSheetSyncRoute = ApiCronSheetSyncRouteImport.update({
  id: '/api/cron/sheet-sync',
  path: '/api/cron/sheet-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLoansNewRoute = AuthenticatedLoansNewRouteImport.update({
  id: '/loans/new',
  path: '/loans/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoansLoanIdRoute =
  AuthenticatedLoansLoanIdRouteImport.update({
    id: '/loans/$loanId',
    path: '/loans/$loanId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBorrowersNewRoute =
  AuthenticatedBorrowersNewRouteImport.update({
    id: '/borrowers/new',
    path: '/borrowers/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBorrowersBorrowerIdRoute =
  AuthenticatedBorrowersBorrowerIdRouteImport.update({
    id: '/borrowers/$borrowerId',
    path: '/borrowers/$borrowerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bin': typeof AuthenticatedBinRoute
  '/capital': typeof AuthenticatedCapitalRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheet': typeof AuthenticatedSheetRoute
  '/portal/$token': typeof PortalTokenRoute
  '/user-payment-acceptance/$consentToken': typeof UserPaymentAcceptanceConsentTokenRoute
  '/borrowers/$borrowerId': typeof AuthenticatedBorrowersBorrowerIdRoute
  '/borrowers/new': typeof AuthenticatedBorrowersNewRoute
  '/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/loans/new': typeof AuthenticatedLoansNewRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/cron/sheet-sync': typeof ApiCronSheetSyncRoute
  '/api/sheet/download': typeof ApiSheetDownloadRoute
  '/borrowers/': typeof AuthenticatedBorrowersIndexRoute
  '/loans/': typeof AuthenticatedLoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bin': typeof AuthenticatedBinRoute
  '/capital': typeof AuthenticatedCapitalRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheet': typeof AuthenticatedSheetRoute
  '/portal/$token': typeof PortalTokenRoute
  '/user-payment-acceptance/$consentToken': typeof UserPaymentAcceptanceConsentTokenRoute
  '/borrowers/$borrowerId': typeof AuthenticatedBorrowersBorrowerIdRoute
  '/borrowers/new': typeof AuthenticatedBorrowersNewRoute
  '/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/loans/new': typeof AuthenticatedLoansNewRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/cron/sheet-sync': typeof ApiCronSheetSyncRoute
  '/api/sheet/download': typeof ApiSheetDownloadRoute
  '/borrowers': typeof AuthenticatedBorrowersIndexRoute
  '/loans': typeof AuthenticatedLoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bin': typeof AuthenticatedBinRoute
  '/_authenticated/capital': typeof AuthenticatedCapitalRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sheet': typeof AuthenticatedSheetRoute
  '/portal/$token': typeof PortalTokenRoute
  '/user-payment-acceptance/$consentToken': typeof UserPaymentAcceptanceConsentTokenRoute
  '/_authenticated/borrowers/$borrowerId': typeof AuthenticatedBorrowersBorrowerIdRoute
  '/_authenticated/borrowers/new': typeof AuthenticatedBorrowersNewRoute
  '/_authenticated/loans/$loanId': typeof AuthenticatedLoansLoanIdRoute
  '/_authenticated/loans/new': typeof AuthenticatedLoansNewRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/cron/sheet-sync': typeof ApiCronSheetSyncRoute
  '/api/sheet/download': typeof ApiSheetDownloadRoute
  '/_authenticated/borrowers/': typeof AuthenticatedBorrowersIndexRoute
  '/_authenticated/loans/': typeof AuthenticatedLoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/bin'
    | '/capital'
    | '/collections'
    | '/dashboard'
    | '/payments'
    | '/settings'
    | '/sheet'
    | '/portal/$token'
    | '/user-payment-acceptance/$consentToken'
    | '/borrowers/$borrowerId'
    | '/borrowers/new'
    | '/loans/$loanId'
    | '/loans/new'
    | '/api/cron/reminders'
    | '/api/cron/sheet-sync'
    | '/api/sheet/download'
    | '/borrowers/'
    | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/bin'
    | '/capital'
    | '/collections'
    | '/dashboard'
    | '/payments'
    | '/settings'
    | '/sheet'
    | '/portal/$token'
    | '/user-payment-acceptance/$consentToken'
    | '/borrowers/$borrowerId'
    | '/borrowers/new'
    | '/loans/$loanId'
    | '/loans/new'
    | '/api/cron/reminders'
    | '/api/cron/sheet-sync'
    | '/api/sheet/download'
    | '/borrowers'
    | '/loans'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/analytics'
    | '/_authenticated/bin'
    | '/_authenticated/capital'
    | '/_authenticated/collections'
    | '/_authenticated/dashboard'
    | '/_authenticated/payments'
    | '/_authenticated/settings'
    | '/_authenticated/sheet'
    | '/portal/$token'
    | '/user-payment-acceptance/$consentToken'
    | '/_authenticated/borrowers/$borrowerId'
    | '/_authenticated/borrowers/new'
    | '/_authenticated/loans/$loanId'
    | '/_authenticated/loans/new'
    | '/api/cron/reminders'
    | '/api/cron/sheet-sync'
    | '/api/sheet/download'
    | '/_authenticated/borrowers/'
    | '/_authenticated/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalTokenRoute: typeof PortalTokenRoute
  UserPaymentAcceptanceConsentTokenRoute: typeof UserPaymentAcceptanceConsentTokenRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
  ApiCronSheetSyncRoute: typeof ApiCronSheetSyncRoute
  ApiSheetDownloadRoute: typeof ApiSheetDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-payment-acceptance/$consentToken': {
      id: '/user-payment-acceptance/$consentToken'
      path: '/user-payment-acceptance/$consentToken'
      fullPath: '/user-payment-acceptance/$consentToken'
      preLoaderRoute: typeof UserPaymentAcceptanceConsentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sheet': {
      id: '/_authenticated/sheet'
      path: '/sheet'
      fullPath: '/sheet'
      preLoaderRoute: typeof AuthenticatedSheetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capital': {
      id: '/_authenticated/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof AuthenticatedCapitalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bin': {
      id: '/_authenticated/bin'
      path: '/bin'
      fullPath: '/bin'
      preLoaderRoute: typeof AuthenticatedBinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans/': {
      id: '/_authenticated/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof AuthenticatedLoansIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/borrowers/': {
      id: '/_authenticated/borrowers/'
      path: '/borrowers'
      fullPath: '/borrowers/'
      preLoaderRoute: typeof AuthenticatedBorrowersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/sheet/download': {
      id: '/api/sheet/download'
      path: '/api/sheet/download'
      fullPath: '/api/sheet/download'
      preLoaderRoute: typeof ApiSheetDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sheet-sync': {
      id: '/api/cron/sheet-sync'
      path: '/api/cron/sheet-sync'
      fullPath: '/api/cron/sheet-sync'
      preLoaderRoute: typeof ApiCronSheetSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/loans/new': {
      id: '/_authenticated/loans/new'
      path: '/loans/new'
      fullPath: '/loans/new'
      preLoaderRoute: typeof AuthenticatedLoansNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loans/$loanId': {
      id: '/_authenticated/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof AuthenticatedLoansLoanIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/borrowers/new': {
      id: '/_authenticated/borrowers/new'
      path: '/borrowers/new'
      fullPath: '/borrowers/new'
      preLoaderRoute: typeof AuthenticatedBorrowersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/borrowers/$borrowerId': {
      id: '/_authenticated/borrowers/$borrowerId'
      path: '/borrowers/$borrowerId'
      fullPath: '/borrowers/$borrowerId'
      preLoaderRoute: typeof AuthenticatedBorrowersBorrowerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBinRoute: typeof AuthenticatedBinRoute
  AuthenticatedCapitalRoute: typeof AuthenticatedCapitalRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSheetRoute: typeof AuthenticatedSheetRoute
  AuthenticatedBorrowersBorrowerIdRoute: typeof AuthenticatedBorrowersBorrowerIdRoute
  AuthenticatedBorrowersNewRoute: typeof AuthenticatedBorrowersNewRoute
  AuthenticatedLoansLoanIdRoute: typeof AuthenticatedLoansLoanIdRoute
  AuthenticatedLoansNewRoute: typeof AuthenticatedLoansNewRoute
  AuthenticatedBorrowersIndexRoute: typeof AuthenticatedBorrowersIndexRoute
  AuthenticatedLoansIndexRoute: typeof AuthenticatedLoansIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBinRoute: AuthenticatedBinRoute,
  AuthenticatedCapitalRoute: AuthenticatedCapitalRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSheetRoute: AuthenticatedSheetRoute,
  AuthenticatedBorrowersBorrowerIdRoute: AuthenticatedBorrowersBorrowerIdRoute,
  AuthenticatedBorrowersNewRoute: AuthenticatedBorrowersNewRoute,
  AuthenticatedLoansLoanIdRoute: AuthenticatedLoansLoanIdRoute,
  AuthenticatedLoansNewRoute: AuthenticatedLoansNewRoute,
  AuthenticatedBorrowersIndexRoute: AuthenticatedBorrowersIndexRoute,
  AuthenticatedLoansIndexRoute: AuthenticatedLoansIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalTokenRoute: PortalTokenRoute,
  UserPaymentAcceptanceConsentTokenRoute:
    UserPaymentAcceptanceConsentTokenRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
  ApiCronSheetSyncRoute: ApiCronSheetSyncRoute,
  ApiSheetDownloadRoute: ApiSheetDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
